### ISSUE TITLE
[Tokenizer] Use bigger HTML for performance benchmarks

### ISSUE THREAD

**Issue by kkebo** [kkebo/zyphy#17]
I'm currently measuring performance by using the following small HTML, but I should replace it with a bigger HTML for more accurate benchmarks.

https://github.com/kkk669/zyphy/blob/b95c9d11fe4641dba3257c9e75ed412fb492049e/Benchmarks/Benchmarks/MyBenchmark/MyBenchmark.swift#L15-L26

And I would like to compare Zyphy's tokenizer with other high-performance HTML tokenizers if possible.

**Comment by kkk669** [comment]
In case of html5ever,

https://github.com/servo/html5ever/blob/master/html5ever/benches/html5ever.rs

**Comment by kkk669** [comment]
In the case of htm5lgum,

https://github.com/untitaker/html5gum/blob/main/benches/patterns.rs

**Comment by kkk669** [comment]
In the case of html-parse,

https://github.com/bgamari/html-parse

**Comment by kkk669** [comment]
In the case of html-tokenizer,

https://github.com/greim/html-tokenizer/blob/master/benchmark/benchmark.js

**Comment by kkk669** [comment]
I think that I don't need a large HTML for the benchmark test of `Tokenizer` because other libraries also use small pieces of HTML for that purpose. Moreover, I can do the benchmark test for the whole browser engine not only for `Tokenizer` when I implement the main module.

Anyway, I should finish #39 first.
